### ISSUE TITLE
[bug] onSentenceComplete not firing

### ISSUE THREAD

**Issue by JohnRSim** [Hagsten/Talkify#10]
onSentenceComplete event doesn't appear to be triggered?
These get triggered fine in order - 

onBeforeItemPlaying
onItemLoaded
onPlay
onPause

```javascript

var player = new talkify.TtsPlayer();

player.subscribeTo({
	onBeforeItemPlaying:function() {
		console.log('onBeforeItemPlaying');
	},
	onPause:function() {
		console.log('onPause');
	},
	onPlay:function() {
		console.log('onPlay');
	},
	onResume:function() {
		console.log('onResume');
	},
	onItemLoaded:function() {
		console.log('onItemLoaded');
	},
	onTextHighligtChanged:function() {
		console.log('onTextHighligtChanged');
	},
	onSentenceComplete:function(item) {
		console.log('onSentenceComplete',item);
	}
});

player.playText('helloWorld');
```

**Comment by Hagsten** [comment]
It seems to be undocumented, but you will need to enable text hightlighting for onSentenceComplete to fire.  And a sense it is not when a sentence completes but rather when a block of text is complete. 

So try to use
`var player = new talkify.TtsPlayer().enableTextHighlighting();`

See if that works. Then one can always discuss whether the event has a bad name or if we should be more intelligent to actually emit the event after a sentence. Or if it should trigger when the audio has ended.
