### ISSUE TITLE
How to make the progress bar clickable?

### ISSUE THREAD

**Issue by technolingo** [Hagsten/Talkify#14]
Hello. I'm trying to achieve two functions: 

One: Make the progress bar **clickable** so that it jumps to that position.

Two: Create a '**go back 5 seconds**' button that does what it sounds like :)

Is it possible to do this? Thank you!

**Comment by Hagsten** [comment]
I am working on this at the moment, the only issue is the speech marks that needs to be adjusted accordingly. I'll see if I can solve this properly.

**Comment by Hagsten** [comment]
Latest version, 2.1.2, now support clicking on the progress bar.

Regarding your "5 seconds back" feature - you can probably implement this yourself by leveraging the click-event of the progress-bar or seeked event on the audio tag (if you are not using our UI).

**Comment by technolingo** [comment]
Could you tell me the code to change the current time? Is it the same as below?

```
//Backtime
$('#audio_backtime').click(function(){
	audio.currentTime -= 5;
});
```

**Comment by technolingo** [comment]
Currently, if I use `player.playText()` to pass a string, the progress bar is not displayed properly and not clickable.

**Comment by Hagsten** [comment]
@evilplanet do you still have this issue? It works fine for me in thie fiddle: https://jsfiddle.net/cs3556zk/1/

Also, you are quite right, you can jump back using your solution, I've used it in this fiddle: https://jsfiddle.net/xt472g3w/1/

And here is an example when using text higlighting and the requested fetaure: https://jsfiddle.net/rvuyjzse/1/

**Comment by technolingo** [comment]
Thank you. Solved.
