### ISSUE TITLE
Style tag in package.json

### ISSUE THREAD

**Issue by yadickson** [Hagsten/Talkify#15]
Hello,

Please, can you add the style field in package.json?

I'm use the gulp-style-npm-files to find css files in node_modules projects.

Example:

  "main": "dist/talkify.js",
  **"style": "dist/styles/*.css",**
  "scripts": {
  ....

Best regards

**Comment by Hagsten** [comment]
I'll have a look at this soon :)

**Comment by Hagsten** [comment]
Done! :)

**Comment by yadickson** [comment]
Thanks a lot!
