### ISSUE TITLE
How to disable pause between elements?

### ISSUE THREAD

**Issue by technolingo** [Hagsten/Talkify#17]
Somehow in my use case, each word is encapsulated by a `span` tag, and if I select all the spans, Talkify will treat them like individual words as opposed to paragraphs. How do I disable the pause between elements? Thank you.

**Comment by Hagsten** [comment]
I am not quite sure I understand, could you elaborate by providing code samples?

**Comment by technolingo** [comment]
```
<p>
<span>Hello</span>
<span>world</span>
<span>!</span>
<span>I</span>
<span>am</span>
<span>using</span>
<span>Talkify</span>
</p>
```
Thank you for responding. In the above example, I want Talkify to treat this paragraph as `Hello world! I am using Talkify`, not `Hello` `world` `!` `I` `am` `using` `Talkify`. How could I achieve that? 

Currently, I'm extracting the text of those spans and calling `player.playText()`, but then I cannot use the playlist features, such as display progress, make progress bar clickable, etc. 

How do I use the playlist features with this html layout? Thank you.

**Comment by Hagsten** [comment]
Hi, according to this fiddle (https://jsfiddle.net/7Lxouoge/1/) it seems to treat your spans as a paragraph. Feel free to modify and re-post the fiddle if I am misunderstanding your issue :).

**Comment by technolingo** [comment]
That's great solution! Though, if I use `.withRootSelector()`, I won't be able to tell Talkify which elements to narrate and which to ignore. Actually, my layout is more complicated than that; I'm sorry I didn't make it clear. For example:

```
<p>
<span>
<ruby><rb>Hello</rb><rp>(</rp>
<rt>ignore me</rt><rp>)</rp>
</ruby>
</span>
<span>
<ruby><rb>world</rb><rp>(</rp>
<rt>ignore me</rt><rp>)</rp>
</ruby>
</span>
</p>
```
How do you tell Talkify to say `Hello world`, not `Hello` `world`, not `Hello ignore me world ignore me` in this case?

**Comment by technolingo** [comment]
It would be nice to be able to ignore certain elements.

**Comment by Hagsten** [comment]
I see your point now. :)

First, Talkify has a set of HTML-elements that it automatically discards. Ruby-elements is a candidate for this set, I'll need to think this through. (see "forbiddenElementsString" in https://raw.githubusercontent.com/Hagsten/Talkify/master/src/talkify-textextractor.js)

Secondly, as you point out, I can add a method that enables exclusion of elements. 

I might do both actually. I'll get back to you when I've got an update.

**Comment by technolingo** [comment]
Thank you. Solved.
