### ISSUE TITLE
I don't know how to use 'forceVoice' API

### ISSUE THREAD

**Issue by limmin5** [Hagsten/Talkify#18]
Hello,

Like subject, I don't know how to use 'forceVoice' API.

I'd like to change voice but I dont know how.

Does anyone tell me?

Thanks in advance.

**Comment by Hagsten** [comment]
Hello,

I've written a short fiddle for you, please have a look at https://jsfiddle.net/v9528q45/

Basically you call the forceVoice method of the player instance, providing an object with a name property. The name property should be assigned the name of the voice, for example 'David'. To get a list of available voices just call https://talkify.net/api/speech/v1/voices?key=[your api key]. Have a look at the fiddle and you will see all this in action :)

Hope it helps!
