### ISSUE TITLE
How to adjust playback speed while playing?

### ISSUE THREAD

**Issue by technolingo** [Hagsten/Talkify#19]
As above, currently, you must request another audio in order to let the new playback rate take effect. How to allow users adjust playback speed while the audio is playing? (TtsPlayer)

**Comment by Hagsten** [comment]
Hi,

The rate is a fixed value for the current audio stream. Thus we can not adjust the rate for the audio stream currently playing.

One solution could be to reload the stream and set its position to the same as before changing rate. But this is nothing we support out of the box at the moment.

**Comment by technolingo** [comment]
Got it. Thanks.
