### ISSUE TITLE
Demo for force voice?

### ISSUE THREAD

**Issue by technolingo** [Hagsten/Talkify#20]
How to force the TtsPlayer to use a designated voice? Could you give me a more detailed example? Thank you!

**Comment by Hagsten** [comment]
Hi,

Have a look at this fiddle: https://jsfiddle.net/mknm62nx/1/

I hope it helps :)

**Comment by technolingo** [comment]
Thanks. It's very helpful.

**Comment by technolingo** [comment]
Will the order of this array ever change? Also, can I store and use the Name string without getting the array every time?

**Comment by technolingo** [comment]
Somehow, if you use forcevoice, the progress bar disappears.

**Comment by Hagsten** [comment]
The order of the array can change, but the name will not (see them as their IDs). You can hard code the voice names you are interested in using :)

**Comment by Hagsten** [comment]
Regarding the progress bar. I've seen it as well, but it seems rather rare, right? I've yet to find the cause of this.

**Comment by technolingo** [comment]
Yeah. Very strange.
