### ISSUE TITLE
Issue with Talkify client side implementation.

### ISSUE THREAD

**Issue by nisharaphael123** [Hagsten/Talkify#21]
Hello all,
We have implemented client side Talkify, in which there is a Play button on clicking the play button, all web voices are loaded using "voices = window.speechSynthesis.getVoices();". In the list of voices first three voices are the desktop voices and other are google remote voices. When we select any voice from top three, speech and highlight functionality are proper, but when we select any remote voice, speech is proper but it highlights only first character of the paragraph. Also if we pause the speech and then resume it, speech will stop from that paragraph, not from there, where we pause the speech. When we select the remote voice only for first load it hit the function updateClock(e), and then not a single time it hit that function. Please help to solve these issues ASAP. Thanks in advance.

> Javascript to load voices.

```
 function loadWebSpeechVoices(inputId) {    
    setTimeout(function () {
        debugger;
        voices = window.speechSynthesis.getVoices();

        var div = $("#talkify_client" + inputId);
        div.show();

        var ul = $("#webSpeechVoices" + inputId);
        ul.show();

        for (var i = 0; i < voices.length; i++) {
            var local = voices[i].localService ? "local" : "remote";
            var li = $("<li>" + voices[i].name + " (" + local + ")</li>");
            li.data('voice', voices[i].name);

            ul.append(li);
        }

        ul.find("li").click(function (e) {
            ul.hide();

            var voice = voices.filter(function (x) { return x.name === $(e.currentTarget).data('voice'); })[0];
            selectedVoice = voice;

            loadWebSpeechPlayer();

            if (playlist) {
                playlist.replayCurrent();
            }
        });
    }, 100);
} 
```

> Function to load player
``` 
function loadPlayer(instance) {
    player = instance.forceVoice(selectedVoice);

    if (useTextHighlighting) {
        player.enableTextHighlighting();
    }

    if (playlist) {
        playlist.setPlayer(player);
    }
} 
```

**Comment by Hagsten** [comment]
Hi!

Lets summarize your questions a bit :)

1. There is no support for resume in the Web Speech player right now, but I'll add it to the list of low hanging fruits. The WebSpeech API seems to have support for resume (https://developer.mozilla.org/en-US/docs/Web/API/SpeechSynthesis/resume) so I'll try to implement it in our player. 

2. If text highlighting is enabled we will try to highlight for local voices only. It seems that the "boundary" event, which is the event that enables text highlighting, only works for some voices (installed SAPI-voices or via chrome extensions). I've yet not been able to identify which of the local voices do support boundary and which do not. If you select a "remote" voice you will see no attempt on higlighting words.

Just FYI, there is some discussion regarding the onboundary event @https://bugs.chromium.org/p/chromium/issues/detail?id=336769

3. Can you give me more information regarding the updateClock function? There is no code sample provided that includes that function.
