### ISSUE TITLE
how can i get API for my webAPP

### ISSUE THREAD

**Issue by sidkasundra** [Hagsten/Talkify#24]
I want to integrate in my angular 2 website.

**Comment by Hagsten** [comment]
Hi!

You can find examples in our readme file if you are talking about our Javascript library. If you are talking about our speech api you will find documentation at https://manage.talkify.net/docs. 

You will need an api key (from https://manage.talkify.net) for this library to work, unless targetting the browser integrated voices.

My answer is very generic so please specify your question for a more specific answer :)
