### ISSUE TITLE
German example sentence

### ISSUE THREAD

**Issue by Toniiiio** [Hagsten/Talkify#26]
Great tool!

Just a small remark:
In your fiddle it is written:
"Hey, ich kann sehr hilfreich sein, wenn Sie versuchen, Deutsch zu lernen werden"

Correct German would be:
"Hey, ich kann sehr hilfreich sein, wenn Sie versuchen Deutsch zu lernen."

(I am born and raised in Germany).

**Comment by Hagsten** [comment]
Thank you, i've adjusted the fiddle :).
