### ISSUE TITLE
What about Italian language support?

### ISSUE THREAD

**Issue by fabiocaccamo** [Hagsten/Talkify#29]

**Comment by Hagsten** [comment]
There is an Italian voice "Lucia". Does that work for you? :)

**Comment by fabiocaccamo** [comment]
I need male and female voices for this languages: 
English, French, German, Spanish, Portuguese, Italian

**Comment by Hagsten** [comment]
Sorry, the voices we support are those available at https://talkify.net. Not all languages have male and female voices.

**Comment by fabiocaccamo** [comment]
Ok, thanks.
