### ISSUE TITLE
Play simple text?

### ISSUE THREAD

**Issue by glittle** [Hagsten/Talkify#3]
The readme talks about `Play simple text` with `talkify.playText('Hello world');`.

However, there is no instruction on how to create `talkify`. Is it implicitly added to the `window` object?

**Comment by Hagsten** [comment]
Hi, I have updated that section of the readme now. You need to instantiate (or use an existing) a player and then invoke the playText method on the player specifying a string.

var player = new TtsPlayer(); //or new Html5Player()
player.playText('Hello world');

Does that do the trick for you? :)
