### ISSUE TITLE
Get the current item in the playlist being played

### ISSUE THREAD

**Issue by debjyoti88** [Hagsten/Talkify#30]
Hi Hagsten, 

Thank you for the api. I'm using it for my research and have found it very useful so far. I wanted to ask you if there's any way to retrieve the current item in the playlist the talkify TTS is currently playing.

**Comment by debjyoti88** [comment]
Also, if I use the player.playText instead of the playlist, is there a way to retrieve the word/position in the text that is currently being read by the TTS ?

**Comment by Hagsten** [comment]
Hi, 

You could find the current item by playlist.getQueue() and then fllter on isPlaying. You could also listen to the player event onBeforeItemPlaying which will pass the current item in the callback.

Hope it helps :)

**Comment by debjyoti88** [comment]
Great, thanks! However, I'm facing a problem with the playlist. The pause between consecutive items in the playlist is a bit too long for my requirement. I cannot happen to reduce that pause. The pause is significantly longer than playing with playText().

**Comment by Hagsten** [comment]
There should not be any difference really. How long time are we talking? Is it a long pause in the audio stream itself or some client side delay?
