### ISSUE TITLE
is the API still working?

### ISSUE THREAD

**Issue by Omrize** [Hagsten/Talkify#31]
Hello, i tried using the API but it is not working for me.
the following error appears after the request : 
"Server Error in '/' Application.
The resource cannot be found.
Description: HTTP 404. The resource you are looking for (or one of its dependencies) could have been removed, had its name changed, or is temporarily unavailable.  Please review the following URL and make sure that it is spelled correctly. 
Requested URL: /9bd1e06b-7e47-4959-a095-a47352d0b88a/speech/v1"

I'm mostly interested in the download feature that the api provides.
is there an option to download the generated speech in talkify.js library?

**Comment by Hagsten** [comment]
Hi, the URL is https://talkify.net/api/speech/v1. You can find all our endpoints at https://manage.talkify.net/docs :).

You can download our audio by, for example, pointing an anchor tag to our speech endpoint or by using a form element with a Post action to our download endpoint (see our docs). 

Hope it helps!
