### ISSUE TITLE
Image Alt Tags

### ISSUE THREAD

**Issue by austin-powell** [Hagsten/Talkify#33]
Is there a way to make talkify read the alt tags of images or fallback text of objects instead of just completely skipping over them? More like a screen reader does?

**Comment by Hagsten** [comment]
@austin-powell not at the momeny no. But it is a good idea.

**Comment by Hagsten** [comment]
https://github.com/Hagsten/Talkify/pull/68

**Comment by Hagsten** [comment]
This is not generally available since v4.0.0
