### ISSUE TITLE
forceLanguage on hosted player

### ISSUE THREAD

**Issue by ivan-kleshnin** [Hagsten/Talkify#34]
Hi! What is the reason of `forceLanguage` and `setVolume` being available only on Html5 player and not on the hosted one? The latter seems to provide much better voice experience but I really need this cut functionality :)

**Comment by Hagsten** [comment]
Hi!

Regarding forceLanguage, you should use forceVoice instead for the hosted voice. There is no support for selecting a voice based on culture (like the html5 version does) in the Js/backend Api - you could do this yourself by calling the voice endpoint and select one based on the culture property. I agree that it would be better to streamline the Api between the types of voices, but for now you need to use forceVoice.

The volume is always 100% (maximum) in the output from our backend. There is no support to change that programatically but rather one would rely on the client volume control (for example the audio tag in modern browsers).

Hope it helps :)
