### ISSUE TITLE
Release backend code?

### ISSUE THREAD

**Issue by sammdu** [Hagsten/Talkify#35]
Hi!

Love your project! I plan to use this in a recent project of mine, and this script will improve the workflow significantly.

However, I see your script is dependent on a back-end, but I don't see the code for the back-end server that I can use to host it myself.

Do you plan to release the source code for the back-end server so people can have it self-hosted? Or is it going to remain an API service for the foreseeable future?

Would really appreciate if you make it possible to host the back-end myself.

Thanks!

**Comment by Hagsten** [comment]
Hi!

Thank you for your kind words :). 

Our backend is not open source. We charge usage of our API for all except the users of talkify.net.

It is unlikly that we will release the source, but this project could in theory be used against backend such as Amazon, google or Microsoft.
