### ISSUE TITLE
How to make this work?

### ISSUE THREAD

**Issue by Uup115** [Hagsten/Talkify#37]
Hello,

So, I have my API-KEY.  Unfortunately, I have no success with getting it to work.  

Using Google Chrome:
https://talkify.net/api/speech/v1?text=Hello world&key=MY_API_KEY 

Returns:
HTTP ERROR 400

Please, what am I doing wrong?

Best Regards

**Comment by Hagsten** [comment]
Hi, are you calling from a browser or from your backend?

You can also send me your details to contact@talkify.net so i can assist further.

**Comment by Hagsten** [comment]
This issue was resolved in a new release of the Talkify API.
