### ISSUE TITLE
Issue capturing credit card details on website

### ISSUE THREAD

**Issue by Fourty5Dev** [Hagsten/Talkify#42]
Good day,

I'm having trouble adding my Credit Card details to your site (under "Pay for what you use"). It keeps telling me that an error has occurred. I used the same card to purchase Credits (different payment page) without any issues but this is only a short-term solution as we need to subscribe to a monthly package. 

I tried sending an email but it keeps getting returned. 

Regards,
Tean

**Comment by Hagsten** [comment]
Hi,

Can you write to contact@talkify.net since this has nothing to do with this library? I will take care of your issue once your email arrives.

**Comment by Fourty5Dev** [comment]
Hi,

I tried but my messages keep getting sent back.

[image: image.png]

**Comment by Hagsten** [comment]
Alright, give me an email address where I can reach you :)

**Comment by Fourty5Dev** [comment]
Hi,

Thank you so much. You can reach me at teangouws@gmail.com

Regards,
Tean
