### ISSUE TITLE
forceVoice()

### ISSUE THREAD

**Issue by PikeAngler** [Hagsten/Talkify#45]
Documentation states the parameter should be a JSON object with name property from /api/speech/v1/voices.
But what is the actual format of the JSON object to pass to the function?
Is it {name: "/api/speech/v1/voices/Naja (Danish da-DK)"}?
and should my api-key be included as property also?

I intend to play sound directly from a button event with text I supply (max 10 words) - no reading from a page or a form and without any player controls visible.

By the way: I have supplied my api key in:
talkify.config = {
		remoteService: {
			host: 'https://talkify.net',
			apiKey: '(my key)',
			speechBaseUrl: '/api/speech/v1',
			languageBaseUrl: '/api/language/v1',
			active: true
			},
			ui: {
				audioControls:{
				enabled: false
			}
		}
	}

and in initalization of the player:
var player = new talkify.TtsPlayer({key: ((myKey)) });
const sayIt = () => {
		player.forceVoice({name: 'Mads'});
		player.playText(example);
	}

- but still get error messages: No subscriber found (a key that is NOT mine).player.*.ratechanged
- similar for prepareplay
When not setting voice, 
when using forceVoice, also for: voiceset.

I can play when not using forceVoice, but when i use player.forceVoice() I get this error:
GET https://talkify.net/api/speech/v1?texttype=text&text=Dette%20er%20et%20eksempel%20p%C3%A5%20dansk%20tale%20med%20r%C3%B8dgr%C3%B8d%20med%20fl%C3%B8de%20og%20s%C3%A5%20videre.&fallbackLanguage=-1&voice=Mads&rate=1&key= ( my key ) &whisper=false&soft=false&wordbreakms=0&volume=0&format=mp3 401 (Unauthorized)

(this is in a Svelte project, but that should not interfere in any way)

**Comment by Hagsten** [comment]
Hi,

I'm on my phone now so I will answer briefly, hopefully it helps - if not I will give a more detailed answer later. 

Parameter to forceVoice should be {name :'Naja'}.

The key should ONLY be included in the configuration. No where else in the API. Not in the init of the player that is. 

The warnings about subscribers are not errors, some events does not have any listeners in some cases. You can turn them off by disabling debug in the configuration. 

Naja is a premium voice, do you have a premium subscription or a pay as you go subscription? If you have a standard subscription then you will be unauthorized to use Naja.

Hope it helps.

**Comment by PikeAngler** [comment]
Hi, thank you for your prompt response. It is really helpful.
I realize that there are only premium Danish voices, and it works fine  
with the Swedish voice.
The pay per use for a premium voice is probably a good solution for me.
By the way:
I don't need an ui, just a consistent Danish voice across browsers and  
platforms to activate from a button click in my app.
Is there a way to avoid the js overhead for Talkify's ui? Maybe do the  
rest calls to the api directly?

Palle

Citat af Hagsten <notifications@github.com>:

**Comment by Hagsten** [comment]
Hi,

Glad it helped! Sorry, there is no JS-package that excludes our controlcenter (the UI). So the overhead of the filesize can not be removed (unless you construct such a package yourself from our source files) but an instance of the controlcenter wont be created (icons will not be loaded).

You can of course exclude our css-files, but the js-file will be included...

You can always opt out from this JS-lib and use our API to tailor your own solution. 

I prefer any support related questions that regards our API to be sent via email (contact@talkify.net for example) since this repo is only for the JS-lib.
