### ISSUE TITLE
How to use Locally (from my own server)?

### ISSUE THREAD

**Issue by BigGitWorld** [Hagsten/Talkify#51]
Hi.
Thank you for this nice library.
I'm going to use the Talkify for a SPA, where I have a large number of notifications that want play their text.
So, How can I integrate the Talkify in my own server without needing to call talkify services?
Best regards

**Comment by Hagsten** [comment]
Hi,

You would need to implement the API-endpoints expected from the lib:

The APIs required:
speechBaseUrl: '/api/speech/v2'
languageBaseUrl: '/api/language/v1'

For Speech you would need to implement an endpoint serving audio streams and one endpoint for speech marks (if needed). Language is not really needed and you could fork this repo and remove calls to it.

You have our API docs at https://manage.talkify.net/docs#api-reference to read up on. You will need to implement their contracts accordingly.

I am closing this issue with this response. Hope it helps :)
