### ISSUE TITLE
Reading floating point numbers

### ISSUE THREAD

**Issue by sheethal-santhosh** [Hagsten/Talkify#59]
Hello,
I have noticed an issue with talkify while reading floating point numbers. The digits after the decimal is auto appended multiple times after the existing numbers. 

For e.g, while reading 1.23 kilograms, it will become 1.232323 kilograms. However, it is reading the 1.23 kilograms correctly. 
@Hagsten Could you please suggest any solutions for this? Thanks 

http://jsfiddle.net/2a5j3e19/4/

<img width="145" alt="Screen Shot 2021-12-13 at 9 51 02 am" src="https://user-images.githubusercontent.com/8149506/145732805-9f73bc75-cd00-4bd0-b92e-d7428a7384db.png">

**Comment by sheethal-santhosh** [comment]
@Hagsten Furthermore, I noticed reading email addresses also has this problem. 
For e.g, while reading msanders@frsts.net.au will append au at the end.
<img width="302" alt="Screen Shot 2021-12-15 at 4 03 53 pm" src="https://user-images.githubusercontent.com/8149506/146126640-98765e52-02bf-45f5-a3f6-cffcdfc64c99.png">

**Comment by sheethal-santhosh** [comment]
@Hagsten do we have any updates on this?

**Comment by Hagsten** [comment]
@sheethal-santhosh sorry for the late response. It is due to the naive way we are identifying sentences, which uses among others "." character. Let me investigate and see if I can make is more intelligent. 

I might also add that the problem only occurs when one is missing a character that ends a sentence (., ?, !, etc). It would work if you would have "1.23 kilograms." But I think we should be able to handle your scenario as well.

**Comment by sheethal-santhosh** [comment]
@Hagsten Thanks for replying. Unfortunately not every time such words or text occurs at the end of the sentence. We would greatly appreciate if you could look into it and let us know if there is any immediate fix to this as our customers are highlighting this issue to us.

**Comment by Hagsten** [comment]
@sheethal-santhosh if you could do some testing on https://github.com/Hagsten/Talkify/tree/hotfix/wordHighlightOnDecimalNumbers/dist I would appreciate it. I'm confident in that it works, so confident that its being tested at our main site (talkify.net) as well.

**Comment by sheethal-santhosh** [comment]
@Hagsten Yes, that works! Thanks a lot for your help.
