### ISSUE TITLE
How to preserve the layout while reading?

### ISSUE THREAD

**Issue by sheethal-santhosh** [Hagsten/Talkify#60]
Hi,

@Hagsten Could you please suggest a workaround to preserve the layout while reading?

For e.g, while reading a poem as in the fiddle below, I would prefer not to change the layout. Thanks in advance.

http://jsfiddle.net/e7qvkbwj/25/

**Comment by Hagsten** [comment]
I would suggest avoiding br tags and use paragraphs instead, that should do the trick :)
