### ISSUE TITLE
Words in Uppercase are spelled out as letters.

### ISSUE THREAD

**Issue by sheethal-santhosh** [Hagsten/Talkify#63]
@Hagsten We have implemented talkify with the voices Amy and Nicole. We have some passages with pronunciation of words emphasised in brackets. Currently, those uppercase words are spelled out instead of reading it as a word. I noticed that when using some other voices like Zira, it is reading the uppercase words properly. 

I have provided an instance from one of our passages below for your reference.
``<p><strong><em>How many of these stringed instruments do you know?</em></strong></p><ul><li>The balalaika (ba lah LIGH kah), a Russian relative of the lute, has a triangular body, three strings and a long &ldquo;neck&rdquo;.</li><li>The bass (BASE), also called the double bass, is the largest member of the violin family. It is played standing, by plucking or using a bow.</li><li>The harpsichord (HARP sih kord) is basically a harp inside a piano frame. Like a piano, it is played with the fingers, by pressing down on keys; but unlike a piano, its keys are attached inside to a mechanism that plucks the strings. (A piano's keys are attached inside to padded hammers that strike the strings.)</li><li>The lute (LOOT) is a relative of the guitar, with a wooden body shaped like half a pear.</li><li>The lyre (LIRE) is an ancient member of the harp family.</li><li>The zither (ZITH ur) is an instrument shaped like a flat box with 30 to 40 strings stretched across it. It is played horizontally with the fingertips or a pick.</li></ul>`
`

Our setting is as below,
````
var player = new talkify.TtsPlayer()
                .enableTextHighlighting()
                .forceVoice({name: readAloudVoice}) //readAloudVoice set from the user settings
                .setRate(readRate)
                .usePhonation("soft"); 

var passageplaylist = new talkify.playlist()
                                .begin()
                                .usingPlayer(player)
                                .withRootSelector('.passage-contents')
                                .build();
````

Could you please provide any suggestion to make similar text read properly using the voices Amy and Nicole.

**Comment by Hagsten** [comment]
Interesting! I can see similar issues online when ppl are using the underlying providers directly.... the issue is most likely at Aws Polly in this case. It can probably be solved with ssml (say as tag) but there are no way to add that to specifc text using this library atm.. I will have a look and see if I can provide functionality to pass this kind of ssml for configured elements. If so, that could solve your issue.

**Comment by sheethal-santhosh** [comment]
@Hagsten Thank you for your prompt response. We would appreciate you looking in to this as our audience are young children who are depending on this to learn to read.

**Comment by sheethal-santhosh** [comment]
@Hagsten Just wondering whether you got any solution to this?

**Comment by Hagsten** [comment]
Not yet, I've been looking at a few approaches. I'll let you know :)

**Comment by Hagsten** [comment]
Update: I have a possible solution for this. Hope to have something for you during next week.

**Comment by Hagsten** [comment]
@sheethal-santhosh could you perhaps see if the new feature in this bransh works for your case? https://github.com/Hagsten/Talkify/tree/feature/read-as-lowercase-setting/dist 

See new declarative setting "data-talkify-read-as-lowercase" https://github.com/Hagsten/Talkify/tree/feature/read-as-lowercase-setting#declarative-settings

**An example**
`The lute (<span data-talkify-read-as-lowercase="true">LOOT</span>) is a relative of the guitar, with a wooden body shaped like half a pear.`

**Comment by sheethal-santhosh** [comment]
@Hagsten Thanks a lot. It is working!
