### ISSUE TITLE
How to load the response data into an HTML5 audio tag

### ISSUE THREAD

**Issue by gazpachu** [Hagsten/Talkify#65]
Hi,

Thanks for your work. I couldn't find in the documentation how to handle the response data from the POST to the API endpoint.

It seems to be returning binary data (rather than an mp3 URL), so I was wondering how should we pass this audio data to the HTML5 audio tag.

Many thanks

<img width="601" alt="Screenshot 2022-06-24 at 0 54 38" src="https://user-images.githubusercontent.com/1721288/175342606-c44b264b-45e4-4a3a-a0bb-bf0ff29222b4.png">

**Comment by Hagsten** [comment]
Hi, you cannot, afaik, use POST endpoints with the HTML audio tag. If you are going to use the audio tag then you are stuck with the GET-endpoint which has some limitations regarding length.
