### ISSUE TITLE
Based on latest update please provide example code for RATE and get VOICE LIST

### ISSUE THREAD

**Issue by inglesuniversal** [Hagsten/Talkify#7]
Hello again, I noticed you made an update to your code explaining on your notes that you can now change the rate from -5 to +5 if I'm not mistaking, could you kindly explain how to adapt it based on the sample code you provided? and also, how can I get the list of voices, in order to be able to change them on the fly or can I have a selection dropdown menu to let the user choose their voice or accent?  (UK, US, etc) thanks.

`talkify.config.host = 'http://talkify.net';

talkify.config.ui.audioControls = {
  enabled: true, //<-- Disable to get the browser built in audio controls
  container: document.getElementById("player-and-voices")
};

$(document).ready(function(){
		var player = new talkify.TtsPlayer()
    		.enableTextHighlighting();

    var playlist = new talkify.playlist()
    		.begin()
    		.usingPlayer(player)
        .withRootSelector('#root')
        .withTextInteraction()
        .build()
        .play();	    
});`

**Comment by Hagsten** [comment]
@inglesuniversal 

In that example, which is live at http://jsfiddle.net/woqw6b6g/48/, you can see that the rate slider is now between -5 and 5. Simply slide it back and forth to adjust the playback speed. If you do not want to use the audio controls you can still set the rate of the player by calling "player.setRate(int value);". The playback speed will be taken into effect for the next playback.

All build in voices can be found by calling http://talkify.net/api/voices (json result). The name and description are subject to change so please do not hard code dependencies towards the names in the API. 

For a list of browser build in voices compatible with the Html5Player simply call "window.speechSynthesis.getVoices()".
