### ISSUE TITLE
[Enhancement] requireJS AMD support.

### ISSUE THREAD

**Issue by JohnRSim** [Hagsten/Talkify#9]
When using requireJS to load in talkify I get the following error promise undefined..
```javascript
require(['talkify'], function() {
					var player = new talkify.TtsPlayer();
					player.playText('Hello world');
				});
```
talkify.js:1095 Uncaught TypeError: Cannot read property 'Promise' of undefined

If I place talkify manually in the header it works fine.
Could you please add requireJS support..

Thanks
J.

**Comment by Hagsten** [comment]
This issue should now be resolved
